os:
  - osx

language: cpp

cache:
  directories:
    - node_modules
    - test/testApp/node_modules
    - $HOME/.electron
    - $HOME/.npm
    - /usr/local/Cellar
    - /Library/Caches/Homebrew
    - /usr/local/Library

before_install:
  - brew update
  - brew upgrade
  - brew install dpkg

install:
- rm -rf ~/.nvm
- git clone https://github.com/creationix/nvm.git ~/.nvm
- source ~/.nvm/nvm.sh
- nvm install 5
- npm install npm -g
- npm -v
- npm prune
- npm update

script:
- npm run compile
- npm run test