os:
  - osx

language: node_js
node_js:
  - '4'
  - '5'

cache:
  - directories:
    - node_modules
    - test/testApp/node_modules
    - $HOME/.electron
    - $HOME/.npm

install:
- npm prune
- npm install
- npm run compile