os:
  - osx

language: cpp

cache:
  directories:
    - node_modules
    - test/testApp/node_modules
    - $HOME/.electron
    - $HOME/.npm

install:
- npm prune
- npm install
- npm run compile
- rm -rf ~/.nvm
- git clone https://github.com/creationix/nvm.git ~/.nvm
- source ~/.nvm/nvm.sh
- nvm install 5

script:
- npm run test