platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 5 x64
  - npm prune
  - npm install

build_script:
  - node --version
  - npm --version
  - npm run compile
  - npm run test

build: off